---

variables:
  SRC_DIR: srcproject
  TAR_NAME: ${APP_NAME}.tar.gz
  APP_NAME: symfonyhello
  TARGET_DIR: ${CI_PROJECT_DIR}/ansible



stages:
  - build
  - test 
  - deploy 


build_job:
  stage: build
  image:
    name: php:7.4-alpine
    entrypoint: [""]
  script:
    - apk add gettext libintl git
    - cd ${SRC_DIR}
    - touch .env.${ENV} .env.template
    - envsubst < .env.template >> .env
    - envsubst < .env.${ENV} >> .env
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer 
    - cd ..
    - mkdir app
    - tar czf app/${TAR_NAME} ${TARGET_DIR} --exclude='.env.*'  --exclude='.git' --exclude='node_modules' .
    - cp app/${TAR_NAME}  ${TARGET_DIR}
  artifacts:
    paths:
      - app/${TAR_NAME}
    expire_in: 2d


test_job:
  stage: test
  image: kariae/symfony-php:latest
  allow_failure: true
  script:  
    - php $SRC_DIR/bin/phpunit
  
  
    
packages_job:
  stage: deploy
  image: ansible/centos7-ansible
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
  script:
    - cd ansible
    - ansible-playbook -e target_dir=${TARGET_DIR} -e tar_file=${TAR_NAME} -e app_name=${APP_NAME} deploy.yml 

