<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5u7C2R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5u7C2R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI5u7C2R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI5u7C2R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI5u7C2R\App_KernelDevDebugContainer([
    'container.build_hash' => 'I5u7C2R',
    'container.build_id' => 'f99fcf39',
    'container.build_time' => 1603789515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI5u7C2R');
