<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6J2Y6sH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6J2Y6sH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6J2Y6sH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6J2Y6sH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6J2Y6sH\App_KernelDevDebugContainer([
    'container.build_hash' => '6J2Y6sH',
    'container.build_id' => '2048e8af',
    'container.build_time' => 1603735665,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6J2Y6sH');
